/**
 * AKR Group Database Seed
 * 
 * Run with: npx prisma db seed
 * Add to package.json:
 * "prisma": {
 *   "seed": "ts-node prisma/seed.ts"
 * }
 */

import { PrismaClient, UserRole, CalculatorType, DisclaimerPage } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // =============================================================================
  // SEED USERS
  // =============================================================================
  console.log('👤 Seeding users...');

  // Hash passwords
  const adminPassword = await bcrypt.hash('Admin@123', 12);
  const advisorPassword = await bcrypt.hash('Advisor@123', 12);

  // Create Admin User
  const admin = await prisma.user.upsert({
    where: { email: 'admin@akrgroup.ae' },
    update: {},
    create: {
      email: 'admin@akrgroup.ae',
      passwordHash: adminPassword,
      role: UserRole.ADMIN,
      name: 'System Administrator',
      phone: '+971501234567',
      isActive: true,
    },
  });
  console.log(`✅ Admin created: ${admin.email}`);

  // Create Advisor User
  const advisor = await prisma.user.upsert({
    where: { email: 'advisor@akrgroup.ae' },
    update: {},
    create: {
      email: 'advisor@akrgroup.ae',
      passwordHash: advisorPassword,
      role: UserRole.ADVISOR,
      name: 'Ahmed Al Mansoori',
      phone: '+971502345678',
      isActive: true,
    },
  });
  console.log(`✅ Advisor created: ${advisor.email}`);

  // =============================================================================
  // SEED DISCLAIMERS
  // All pages: MORTGAGE_CALCULATOR, ROI_CALCULATOR, MUTUAL_FUND_CALCULATOR, PROPERTIES, CONTACT, FOOTER
  // =============================================================================
  console.log('📝 Seeding disclaimers...');

  const disclaimers = [
    {
      key: 'mortgage_calculator_disclaimer',
      title: 'Mortgage Calculator Disclaimer',
      content: `IMPORTANT: This mortgage calculator is provided for informational purposes only.

The calculations generated by this tool are estimates only and do not constitute financial, legal, or professional advice. Actual mortgage terms, interest rates, and payments may vary significantly based on your individual circumstances, credit history, and lender requirements.

Key Points to Consider:
• Interest rates are subject to change without notice
• Monthly payments may include principal, interest, taxes, and insurance (PITI)
• Actual loan approval depends on comprehensive financial assessment by the lender
• Processing fees, setup charges, and other costs may apply
• Property valuation is required for final loan approval

AKR Group and its affiliates accept no responsibility for decisions made based on this calculator's output. We strongly recommend consulting with a qualified financial advisor and your chosen lender before making any financial commitments.

Past performance is not indicative of future results. Real estate investments carry inherent risks, including potential loss of principal.`,
      page: DisclaimerPage.MORTGAGE_CALCULATOR,
      active: true,
    },
    {
      key: 'roi_calculator_disclaimer',
      title: 'ROI/XIRR Calculator Disclaimer',
      content: `DISCLAIMER: The ROI and XIRR calculator on this platform is designed for educational and estimation purposes only.

Please note:
• Calculated returns are based on hypothetical scenarios and historical data
• Actual investment returns may differ substantially due to market conditions
• XIRR calculations assume consistent date-based cash flows
• Inflation, taxes, and fees are not factored into these calculations
• Past performance does not guarantee future results

Investment Advisory Notice:
• This tool does not constitute personalized investment advice
• Mutual fund investments are subject to market risks
• Please read all scheme-related documents carefully before investing
• The value of investments can go down as well as up

For accurate financial planning, consult with SEBI-registered investment advisors. AKR Group recommends that you assess your own financial situation and investment objectives before making any investment decisions.`,
      page: DisclaimerPage.ROI_CALCULATOR,
      active: true,
    },
    {
      key: 'mutual_fund_calculator_disclaimer',
      title: 'Mutual Fund Calculator Disclaimer',
      content: `IMPORTANT NOTICE: This mutual fund return calculator provides illustrative examples based on assumed rates of return.

Disclaimer:
• The calculator uses simplified assumptions and may not reflect actual fund performance
• Mutual fund investments are subject to market risks, including possible loss of principal
• NAV (Net Asset Value) values fluctuate based on underlying asset valuations
• SIP (Systematic Investment Plan) returns are subject to market timing risks
• Entry and exit loads, as well as expense ratios, affect actual returns

Regulatory Disclosure:
• This calculator does not consider your specific tax situation
• Tax implications on capital gains vary based on holding period and applicable laws
• Investment decisions should consider your risk appetite, investment horizon, and financial goals

AKR Group advises investors to review the Scheme Information Document (SID), Statement of Additional Information (SAI), and Key Investor Education Documents (KIED) before investing in any mutual fund scheme.

Mutual fund distribution is subject to applicable regulatory requirements.`,
      page: DisclaimerPage.MUTUAL_FUND_CALCULATOR,
      active: true,
    },
    {
      key: 'properties_disclaimer',
      title: 'Properties Listing Disclaimer',
      content: `DISCLAIMER: All property listings on this platform are provided for informational purposes only.

Property Information:
• Descriptions, images, and pricing are provided by listers and should be verified
• Property availability is subject to change without prior notice
• Dimensions, areas, and specifications are approximate
• Prices are quoted in AED (UAE Dirham) unless otherwise specified

No Direct Contact Policy:
• Investors and buyers are prohibited from contacting listers directly
• All inquiries must be routed through AKR Group authorized representatives
• This policy ensures proper qualification and compliance with UAE real estate regulations

Investment Risks:
• Property values can appreciate or depreciate
• Rental yields mentioned are indicative and not guaranteed
• Legal due diligence is strongly recommended before purchase

AKR Group acts as an intermediary and does not guarantee the accuracy of listing information. All transactions are subject to applicable UAE laws and regulations.`,
      page: DisclaimerPage.PROPERTIES,
      active: true,
    },
    {
      key: 'contact_disclaimer',
      title: 'Contact Form Disclaimer',
      content: `PRIVACY NOTICE: When you submit information through our contact form, you consent to AKR Group processing your personal data.

Data Collection:
• We collect information you voluntarily provide (name, email, phone, message)
• This data is used solely to respond to your inquiries
• Phone numbers may be used for follow-up communications

Data Protection:
• Your information is handled in accordance with UAE data protection laws
• We do not share your personal data with third parties without consent
• You may request deletion of your data at any time

Communication:
• By submitting this form, you agree to receive communications from AKR Group
• We may contact you regarding your inquiry and related services
• You can unsubscribe from marketing communications at any time

For questions about your data, contact our Data Protection Officer.`,
      page: DisclaimerPage.CONTACT,
      active: true,
    },
    {
      key: 'footer_disclaimer',
      title: 'General Website Disclaimer',
      content: `LEGAL NOTICE: By accessing and using the AKR Group website and services, you acknowledge and agree to the following terms.

General Disclaimer:
• The information provided on this website is for general informational purposes only
• AKR Group reserves the right to modify, suspend, or discontinue any aspect of the service
• We make no warranties about the completeness, reliability, or accuracy of information

Investment Advisory:
• Information on this website does not constitute investment advice
• Users are advised to seek independent professional consultation
• Investments in financial instruments carry inherent risks

Third-Party Links:
• This website may contain links to external sites
• AKR Group is not responsible for content on external websites
• Visiting external links is at your own risk

Intellectual Property:
• All content, logos, and materials are property of AKR Group
• Reproduction without explicit written consent is prohibited

Contact Information:
AKR Group
Email: info@akrgroup.ae
Phone: +971XXXXXXXXX
Address: Dubai, United Arab Emirates

Last Updated: ${new Date().toISOString().split('T')[0]}`,
      page: DisclaimerPage.FOOTER,
      active: true,
    },
  ];

  for (const disclaimer of disclaimers) {
    await prisma.disclaimer.upsert({
      where: { key: disclaimer.key },
      update: {
        title: disclaimer.title,
        content: disclaimer.content,
        page: disclaimer.page,
        active: disclaimer.active,
      },
      create: disclaimer,
    });
    console.log(`✅ Disclaimer created: ${disclaimer.key}`);
  }

  // =============================================================================
  // SEED SAMPLE LEAD (for testing)
  // =============================================================================
  console.log('📋 Seeding sample lead...');

  const sampleLead = await prisma.lead.upsert({
    where: { email: 'test.lead@example.com' },
    update: {},
    create: {
      name: 'Test Lead',
      email: 'test.lead@example.com',
      phone: '+971501234999',
      source: CalculatorType.MORTGAGE,
      advisorId: advisor.id,
      status: 'NEW',
    },
  });
  console.log(`✅ Sample lead created: ${sampleLead.email}`);

  console.log('\n🎉 Database seeding completed successfully!\n');
  console.log('========================================');
  console.log('Default Credentials:');
  console.log('========================================');
  console.log('Admin:   admin@akrgroup.ae  / Admin@123');
  console.log('Advisor: advisor@akrgroup.ae / Advisor@123');
  console.log('========================================\n');
}

main()
  .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
